config/routes.rb
Rails.application.routes.draw do

  resources :quizzes do
    resources :questions
  end

  resources :attempts do
    resources :answers
  end

  match 'public_quizzes', to: "public_quizzes#index", via: [:get]

  get 'quizzes/index'
  get 'quizzes/show'
  get 'quizzes/new'
  get 'quizzes/edit'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:name, :pass_threshold)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= bootstrap_form_for(@quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.number_field :pass_threshold %>
  </div>

  <div class="field">
    <%= form.number_field :allowed_time %>
  </div>

  <div class="field">
    <%= form.check_box :allow_retake %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render "form", quiz: @quiz %>

<%= link_to "Show", @quiz %> |
<%= link_to "Back", quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Your quizzes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Quiz title</th>
      <th>Number of questions</th>
      <th>Total points</th>
      <th>Pass threshold</th>
      <th colspan="3">
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.name %></td>
        <td><%= quiz.questions.count %></td>
        <td><%= quiz.questions.inject(0) { |sum,q| sum + q.points } %></td>
        <td><%= quiz.pass_threshold %></td>
        <td><%= link_to "Show", quiz %></td>
        <td><%= link_to "Edit", edit_quiz_path(quiz) %></td>
        <td><%= link_to "Delete", quiz, method: :delete, data: { confirm: "Are you sure?" }, class: "delete_link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Quiz", new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render "form", quiz: @quiz %>

<%= link_to "Back", quizzes_path %>

app/views/quizzes/show.html.erb
<h2>Quiz: <%= @quiz.name %></h2>
<p>
  <strong>Pass threshold:</strong>
  <%= @quiz.pass_threshold %>
</p>
<p>
  <strong>Allowed time to complete:</strong>
  <%= @quiz.allowed_time %>
</p>
<p>
  <strong>Is it possible to re-take the Quiz?:</strong>
  <%= @quiz.allow_retake ? "Yes" : "No" %>
</p>


<% if @quiz.questions.present? %>
<h2>Questions</h2>
<table  class="table">
  <thead>
    <th>
      Question Text
    </th>
    <th>
      Points
    </th>
<%
  for i in 1..5 do
%>
    <th>
      Alternative <%= i %>
    </th>
<%
  end
%>
    <th>
      Order
    </th>
    <th>
      &nbsp;
    </th>
  </thead>
<%= render @quiz.questions.order("sort_order") %>
</table>
<% end %>

<h2>Add a question:</h2>
<%= bootstrap_form_for([@quiz, question = @quiz.questions.build]) do |form| %>

  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if flash[:errors] && flash[:errors].any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flash[:errors].count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error[0].humanize %> <%= error[1][0] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%
  question = flash[:question] if flash[:question]
%>

  <div class="field">
    <%= form.text_area :question_text, placeholder: "Enter your beautiful question here. For example: how many days are there in a year?", value: question["question_text"], cols: 50, rows: 10 %>
  </div>
<%
  for i in 1..5 do
%>
  <div class="field" style="margin-bottom: 25px;">
    <%= form.text_field "alt_#{i}".to_sym, value: question["alt_#{i}"], label: "Alternative #{i}" %>
    <%= form.check_box "check_#{i}".to_sym, { checked: question["check_#{i}"] == "1", label: "Correct (yes/no)", inline: true } %>
  </div>
<%
  end
%>
  <div class="field">
    <%= form.number_field :points, value: question["points"], label: "Points assigned to the question" %>
  </div>
  <div class="field">
    <%= form.number_field :sort_order, value: question["sort_order"] %>
  </div>

  <%= form.hidden_field :quiz_id, value: @quiz.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "Edit", edit_quiz_path(@quiz) %> |
<%= link_to "Back", quizzes_path %>