config/routes.rb
Rails.application.routes.draw do

  resources :quizzes do
    resources :questions
  end

  resources :attempts do
    resources :answers
  end

  match 'public_quizzes', to: "public_quizzes#index", via: [:get]

  get 'quizzes/index'
  get 'quizzes/show'
  get 'quizzes/new'
  get 'quizzes/edit'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/views/shared/_carousel.html.erb
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="/slide-1.jpg" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Test your skills with us!</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><%= link_to "Sign up today!", new_registration_path(User), class: "btn btn-lg btn-primary", role: "button" %></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="/slide-2.jpg"  alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Guide your students towards perfection.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Create your first Quiz!</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="/slide-3.jpg"   alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Measure results, improve your teaching.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Manage your quizzes</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>